server:
  port: 33333
  ssl:
    enabled: true
    key-store: d:/tomcat.keystore
    key-store-type: JKS
    key-password: 123456
    key-store-password: 123456
    key-alias: tomcat
    protocol: TLS
  servlet:
    context-path: /wg

spring:
#  security:
#    user:
#      name: wg
#      password: 123
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wg?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms
    password: ''
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

report:
  dir: E:\pandoc-2.16.1\wg\

# 程序监控
management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
      status:
        http-mapping: # 设置不同健康状态对应的响应状态码
          DOWN: 503
        order: FATAL, DOWN, OUT_OF_SERVICE, UP, UNKNOWN # 状态排序

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:wg/application/mapper/xml/*Mapper.xml

logging:
  config: classpath:logback-spring.xml

grpc:
  assessment: localhost:8867

wg:
  jwt:
    secret: Fr0WK4WppCqKRZKuMakH8qvbZ9HuFyg5
    header: X-Auth-Token