 server:
  port: 33333
  ssl:
    enabled: true
    key-store: d:/tomcat.keystore
    key-store-type: JKS
    key-password: 123456
    key-store-password: 123456
    key-alias: tomcat
    protoclo: TLS

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  security:
#    user:
#      name: admin
#      password: 123
#      roles: admin

report:
  dir: E:\pandoc-2.16.1\wg

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:wg/application/mapper/xml/*Mapper.xml

wg:
  test: 111









