server:
  port: 33333

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beichen?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver









