# \u914D\u7F6E https
server:
  port: 33335
  ssl:
    enabled: true
    key-store: /usr/local/keystore/https-wg.keystore
    key-alias: https-wg
    key-store-type: PKCS12
    key-password: 123456
    key-store-password: 123456
    protocol: TLS
  servlet:
    context-path: /wg
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wg?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:wg/application/mapper/xml/*Mapper.xml

logging:
  config: classpath:logback-spring.xml

report:
  dir: /data/sevenme/report/

wg:
  jwt:
    secret: Fr0WK4WppCqKRZKuMakH8qvbZ9HuFyg5
    header: X-Auth-Token


