# \u914D\u7F6E https
server:
  port: 33333
  ssl:
    enabled: true
    key-store: /usr/local/keystore/https-wg.keystore
    key-alias: https-wg
    key-store-type: PKCS12
    key-password: 123456
    key-store-password: 123456
    protocol: TLS
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wg?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

report:
  dir: /data/sevenme/report/


