server:
  port: 33333
  ssl:
    enabled: true
    key-store: d:/tomcat.keystore
    key-store-type: JKS
    key-password: 123456
    key-store-password: 123456
    key-alias: tomcat
    protoclo: TLS

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wg?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  security:
#    user:
#      name: admin
#      password: 123
#      roles: admin

report:
  dir: E:\pandoc-2.16.1\wg\

# 程序监控
management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
      status:
        http-mapping: # 设置不同健康状态对应的响应状态码
          DOWN: 503
        order: FATAL, DOWN, OUT_OF_SERVICE, UP, UNKNOWN # 状态排序