package wg.application.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wg.application.entity.DocumentFile;
import wg.application.entity.DocumentFileExample;

public interface DocumentFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    long countByExample(DocumentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    int deleteByExample(DocumentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    int insert(DocumentFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    int insertSelective(DocumentFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    List<DocumentFile> selectByExample(DocumentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    DocumentFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DocumentFile record, @Param("example") DocumentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DocumentFile record, @Param("example") DocumentFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DocumentFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DocumentFile record);
}