package wg.application.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wg.application.entity.FileMy;
import wg.application.entity.FileMyExample;

public interface FileMyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_my
     *
     * @mbg.generated
     */
    long countByExample(FileMyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_my
     *
     * @mbg.generated
     */
    int deleteByExample(FileMyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_my
     *
     * @mbg.generated
     */
    int insert(FileMy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_my
     *
     * @mbg.generated
     */
    int insertSelective(FileMy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_my
     *
     * @mbg.generated
     */
    List<FileMy> selectByExample(FileMyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_my
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FileMy record, @Param("example") FileMyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_my
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FileMy record, @Param("example") FileMyExample example);
}