package wg.application.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wg.application.entity.Test03;
import wg.application.entity.Test03Example;

public interface Test03Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    long countByExample(Test03Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    int deleteByExample(Test03Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    int insert(Test03 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    int insertSelective(Test03 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    List<Test03> selectByExample(Test03Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    Test03 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Test03 record, @Param("example") Test03Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Test03 record, @Param("example") Test03Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Test03 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_03
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Test03 record);
}