package wg.application.entity;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   存放文件的
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table file_my
 */
public class FileMy {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_my.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_my.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     * Database Column Remarks:
     *   文件后缀
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_my.suffix
     *
     * @mbg.generated
     */
    private String suffix;

    /**
     * Database Column Remarks:
     *   文件绝对路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_my.absolute_path
     *
     * @mbg.generated
     */
    private String absolutePath;

    /**
     * Database Column Remarks:
     *   文件大小(k)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_my.length
     *
     * @mbg.generated
     */
    private Long length;

    /**
     * Database Column Remarks:
     *   sha256值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_my.sha256
     *
     * @mbg.generated
     */
    private String sha256;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_my.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_my.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * Database Column Remarks:
     *   删除标志位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_my.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_my.id
     *
     * @return the value of file_my.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_my.id
     *
     * @param id the value for file_my.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_my.file_name
     *
     * @return the value of file_my.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_my.file_name
     *
     * @param fileName the value for file_my.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_my.suffix
     *
     * @return the value of file_my.suffix
     *
     * @mbg.generated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_my.suffix
     *
     * @param suffix the value for file_my.suffix
     *
     * @mbg.generated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_my.absolute_path
     *
     * @return the value of file_my.absolute_path
     *
     * @mbg.generated
     */
    public String getAbsolutePath() {
        return absolutePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_my.absolute_path
     *
     * @param absolutePath the value for file_my.absolute_path
     *
     * @mbg.generated
     */
    public void setAbsolutePath(String absolutePath) {
        this.absolutePath = absolutePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_my.length
     *
     * @return the value of file_my.length
     *
     * @mbg.generated
     */
    public Long getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_my.length
     *
     * @param length the value for file_my.length
     *
     * @mbg.generated
     */
    public void setLength(Long length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_my.sha256
     *
     * @return the value of file_my.sha256
     *
     * @mbg.generated
     */
    public String getSha256() {
        return sha256;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_my.sha256
     *
     * @param sha256 the value for file_my.sha256
     *
     * @mbg.generated
     */
    public void setSha256(String sha256) {
        this.sha256 = sha256;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_my.create_time
     *
     * @return the value of file_my.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_my.create_time
     *
     * @param createTime the value for file_my.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_my.update_time
     *
     * @return the value of file_my.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_my.update_time
     *
     * @param updateTime the value for file_my.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_my.del_flag
     *
     * @return the value of file_my.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_my.del_flag
     *
     * @param delFlag the value for file_my.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_my
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fileName=").append(fileName);
        sb.append(", suffix=").append(suffix);
        sb.append(", absolutePath=").append(absolutePath);
        sb.append(", length=").append(length);
        sb.append(", sha256=").append(sha256);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append("]");
        return sb.toString();
    }
}