package wg.application.entity;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table picture
 */
public class Picture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     * Database Column Remarks:
     *   1: true   0: false
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.is_private
     *
     * @mbg.generated
     */
    private Integer isPrivate;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.hex_hash
     *
     * @mbg.generated
     */
    private String hexHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.create_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.update_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.create_user_id
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.update_user_id
     *
     * @mbg.generated
     */
    private Integer updateUserId;

    /**
     * Database Column Remarks:
     *   删除位 null: 已删除  0: 未删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.del_flag
     *
     * @mbg.generated
     */
    private Integer delFlag;

    /**
     * Database Column Remarks:
     *   专辑
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.album
     *
     * @mbg.generated
     */
    private String album;

    /**
     * Database Column Remarks:
     *   歌手
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.singer
     *
     * @mbg.generated
     */
    private String singer;

    /**
     * Database Column Remarks:
     *   后缀
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.suffix
     *
     * @mbg.generated
     */
    private String suffix;

    /**
     * Database Column Remarks:
     *   是否翻唱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.is_cover
     *
     * @mbg.generated
     */
    private String isCover;

    /**
     * Database Column Remarks:
     *   发行日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.issue_date
     *
     * @mbg.generated
     */
    private LocalDateTime issueDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.id
     *
     * @return the value of picture.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.id
     *
     * @param id the value for picture.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.name
     *
     * @return the value of picture.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.name
     *
     * @param name the value for picture.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.location
     *
     * @return the value of picture.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.location
     *
     * @param location the value for picture.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.is_private
     *
     * @return the value of picture.is_private
     *
     * @mbg.generated
     */
    public Integer getIsPrivate() {
        return isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.is_private
     *
     * @param isPrivate the value for picture.is_private
     *
     * @mbg.generated
     */
    public void setIsPrivate(Integer isPrivate) {
        this.isPrivate = isPrivate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.desc
     *
     * @return the value of picture.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.desc
     *
     * @param desc the value for picture.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.hex_hash
     *
     * @return the value of picture.hex_hash
     *
     * @mbg.generated
     */
    public String getHexHash() {
        return hexHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.hex_hash
     *
     * @param hexHash the value for picture.hex_hash
     *
     * @mbg.generated
     */
    public void setHexHash(String hexHash) {
        this.hexHash = hexHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.create_datetime
     *
     * @return the value of picture.create_datetime
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.create_datetime
     *
     * @param createDatetime the value for picture.create_datetime
     *
     * @mbg.generated
     */
    public void setCreateDatetime(LocalDateTime createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.update_datetime
     *
     * @return the value of picture.update_datetime
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.update_datetime
     *
     * @param updateDatetime the value for picture.update_datetime
     *
     * @mbg.generated
     */
    public void setUpdateDatetime(LocalDateTime updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.create_user_id
     *
     * @return the value of picture.create_user_id
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.create_user_id
     *
     * @param createUserId the value for picture.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.update_user_id
     *
     * @return the value of picture.update_user_id
     *
     * @mbg.generated
     */
    public Integer getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.update_user_id
     *
     * @param updateUserId the value for picture.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(Integer updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.del_flag
     *
     * @return the value of picture.del_flag
     *
     * @mbg.generated
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.del_flag
     *
     * @param delFlag the value for picture.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.album
     *
     * @return the value of picture.album
     *
     * @mbg.generated
     */
    public String getAlbum() {
        return album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.album
     *
     * @param album the value for picture.album
     *
     * @mbg.generated
     */
    public void setAlbum(String album) {
        this.album = album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.singer
     *
     * @return the value of picture.singer
     *
     * @mbg.generated
     */
    public String getSinger() {
        return singer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.singer
     *
     * @param singer the value for picture.singer
     *
     * @mbg.generated
     */
    public void setSinger(String singer) {
        this.singer = singer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.suffix
     *
     * @return the value of picture.suffix
     *
     * @mbg.generated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.suffix
     *
     * @param suffix the value for picture.suffix
     *
     * @mbg.generated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.is_cover
     *
     * @return the value of picture.is_cover
     *
     * @mbg.generated
     */
    public String getIsCover() {
        return isCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.is_cover
     *
     * @param isCover the value for picture.is_cover
     *
     * @mbg.generated
     */
    public void setIsCover(String isCover) {
        this.isCover = isCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.issue_date
     *
     * @return the value of picture.issue_date
     *
     * @mbg.generated
     */
    public LocalDateTime getIssueDate() {
        return issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.issue_date
     *
     * @param issueDate the value for picture.issue_date
     *
     * @mbg.generated
     */
    public void setIssueDate(LocalDateTime issueDate) {
        this.issueDate = issueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", location=").append(location);
        sb.append(", isPrivate=").append(isPrivate);
        sb.append(", desc=").append(desc);
        sb.append(", hexHash=").append(hexHash);
        sb.append(", createDatetime=").append(createDatetime);
        sb.append(", updateDatetime=").append(updateDatetime);
        sb.append(", createUserId=").append(createUserId);
        sb.append(", updateUserId=").append(updateUserId);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", album=").append(album);
        sb.append(", singer=").append(singer);
        sb.append(", suffix=").append(suffix);
        sb.append(", isCover=").append(isCover);
        sb.append(", issueDate=").append(issueDate);
        sb.append("]");
        return sb.toString();
    }
}