package wg.application.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_operation_log
 */
public class UserOperationLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.op_data
     *
     * @mbg.generated
     */
    private String opData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr1
     *
     * @mbg.generated
     */
    private String attr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr2
     *
     * @mbg.generated
     */
    private String attr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr3
     *
     * @mbg.generated
     */
    private String attr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr4
     *
     * @mbg.generated
     */
    private String attr4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr5
     *
     * @mbg.generated
     */
    private String attr5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr6
     *
     * @mbg.generated
     */
    private String attr6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr7
     *
     * @mbg.generated
     */
    private String attr7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr8
     *
     * @mbg.generated
     */
    private String attr8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr9
     *
     * @mbg.generated
     */
    private String attr9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr10
     *
     * @mbg.generated
     */
    private String attr10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr11
     *
     * @mbg.generated
     */
    private String attr11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_operation_log.attr12
     *
     * @mbg.generated
     */
    private String attr12;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.id
     *
     * @return the value of user_operation_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.id
     *
     * @param id the value for user_operation_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.user_id
     *
     * @return the value of user_operation_log.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.user_id
     *
     * @param userId the value for user_operation_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.ip
     *
     * @return the value of user_operation_log.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.ip
     *
     * @param ip the value for user_operation_log.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.op_data
     *
     * @return the value of user_operation_log.op_data
     *
     * @mbg.generated
     */
    public String getOpData() {
        return opData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.op_data
     *
     * @param opData the value for user_operation_log.op_data
     *
     * @mbg.generated
     */
    public void setOpData(String opData) {
        this.opData = opData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr1
     *
     * @return the value of user_operation_log.attr1
     *
     * @mbg.generated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr1
     *
     * @param attr1 the value for user_operation_log.attr1
     *
     * @mbg.generated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr2
     *
     * @return the value of user_operation_log.attr2
     *
     * @mbg.generated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr2
     *
     * @param attr2 the value for user_operation_log.attr2
     *
     * @mbg.generated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr3
     *
     * @return the value of user_operation_log.attr3
     *
     * @mbg.generated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr3
     *
     * @param attr3 the value for user_operation_log.attr3
     *
     * @mbg.generated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr4
     *
     * @return the value of user_operation_log.attr4
     *
     * @mbg.generated
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr4
     *
     * @param attr4 the value for user_operation_log.attr4
     *
     * @mbg.generated
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr5
     *
     * @return the value of user_operation_log.attr5
     *
     * @mbg.generated
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr5
     *
     * @param attr5 the value for user_operation_log.attr5
     *
     * @mbg.generated
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr6
     *
     * @return the value of user_operation_log.attr6
     *
     * @mbg.generated
     */
    public String getAttr6() {
        return attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr6
     *
     * @param attr6 the value for user_operation_log.attr6
     *
     * @mbg.generated
     */
    public void setAttr6(String attr6) {
        this.attr6 = attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr7
     *
     * @return the value of user_operation_log.attr7
     *
     * @mbg.generated
     */
    public String getAttr7() {
        return attr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr7
     *
     * @param attr7 the value for user_operation_log.attr7
     *
     * @mbg.generated
     */
    public void setAttr7(String attr7) {
        this.attr7 = attr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr8
     *
     * @return the value of user_operation_log.attr8
     *
     * @mbg.generated
     */
    public String getAttr8() {
        return attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr8
     *
     * @param attr8 the value for user_operation_log.attr8
     *
     * @mbg.generated
     */
    public void setAttr8(String attr8) {
        this.attr8 = attr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr9
     *
     * @return the value of user_operation_log.attr9
     *
     * @mbg.generated
     */
    public String getAttr9() {
        return attr9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr9
     *
     * @param attr9 the value for user_operation_log.attr9
     *
     * @mbg.generated
     */
    public void setAttr9(String attr9) {
        this.attr9 = attr9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr10
     *
     * @return the value of user_operation_log.attr10
     *
     * @mbg.generated
     */
    public String getAttr10() {
        return attr10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr10
     *
     * @param attr10 the value for user_operation_log.attr10
     *
     * @mbg.generated
     */
    public void setAttr10(String attr10) {
        this.attr10 = attr10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr11
     *
     * @return the value of user_operation_log.attr11
     *
     * @mbg.generated
     */
    public String getAttr11() {
        return attr11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr11
     *
     * @param attr11 the value for user_operation_log.attr11
     *
     * @mbg.generated
     */
    public void setAttr11(String attr11) {
        this.attr11 = attr11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_operation_log.attr12
     *
     * @return the value of user_operation_log.attr12
     *
     * @mbg.generated
     */
    public String getAttr12() {
        return attr12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_operation_log.attr12
     *
     * @param attr12 the value for user_operation_log.attr12
     *
     * @mbg.generated
     */
    public void setAttr12(String attr12) {
        this.attr12 = attr12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_operation_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", ip=").append(ip);
        sb.append(", opData=").append(opData);
        sb.append(", attr1=").append(attr1);
        sb.append(", attr2=").append(attr2);
        sb.append(", attr3=").append(attr3);
        sb.append(", attr4=").append(attr4);
        sb.append(", attr5=").append(attr5);
        sb.append(", attr6=").append(attr6);
        sb.append(", attr7=").append(attr7);
        sb.append(", attr8=").append(attr8);
        sb.append(", attr9=").append(attr9);
        sb.append(", attr10=").append(attr10);
        sb.append(", attr11=").append(attr11);
        sb.append(", attr12=").append(attr12);
        sb.append("]");
        return sb.toString();
    }
}